version: '3'

services:

  consul:
    image: mscblog/consul:latest
    ports:
      - 5300:8080
    networks:
      main:
        aliases:
          - mscblog-consul

  fakes3:
    image: lphoward/fake-s3
    ports:
      - "4569:4569"

networks:
  main:
